-- =================================================================
-- ALX Airbnb Clone Project - Database Seeding Script
-- Description: This script populates the database with realistic
--              sample data for users, properties, bookings, etc.
-- Author: Simon Kimotho
-- Date: June 29, 2025
-- =================================================================

-- Use the target database
-- USE alx_airbnb;

-- To make this script self-contained and repeatable, we will declare
-- variables for our UUIDs. In a real application, these would be
-- generated by the application logic (e.g., using UUID() function).

-- -----------------------------------------------------
-- Define UUIDs for Users
-- -----------------------------------------------------
SET @host_wambui_id = 'a1b2c3d4-e5f6-7890-1234-567890abcdef';
SET @host_okeyo_id = 'b2c3d4e5-f6a7-8901-2345-678901bcdef0';
SET @guest_sandra_id = 'c3d4e5f6-a7b8-9012-3456-789012cdef01';
SET @guest_ali_id = 'd4e5f6a7-b8c9-0123-4567-890123def012';
SET @admin_user_id = 'e5f6a7b8-c9d0-1234-5678-901234ef0123';

-- -----------------------------------------------------
-- Define UUIDs for Properties
-- -----------------------------------------------------
SET @prop_kilimani_id = 'f6a7b8c9-d0e1-2345-6789-012345f01234';
SET @prop_runda_id = 'a7b8c9d0-e1f2-3456-7890-123456012345';
SET @prop_limuru_id = 'b8c9d0e1-f2a3-4567-8901-234567123456';

-- -----------------------------------------------------
-- Define UUIDs for Bookings
-- -----------------------------------------------------
SET @booking1_id = 'c9d0e1f2-a3b4-5678-9012-345678234567';
SET @booking2_id = 'd0e1f2a3-b4c5-6789-0123-456789345678';
SET @booking3_id = 'e1f2a3b4-c5d6-7890-1234-567890456789';


-- -----------------------------------------------------
-- Step 1: Insert Users
-- -----------------------------------------------------
INSERT INTO User (user_id, first_name, last_name, email, password_hash, phone_number, role) VALUES
(@host_wambui_id, 'Grace', 'Wambui', 'grace.wambui@example.com', 'hash_wambui_pwd', '+254722123456', 'host'),
(@host_okeyo_id, 'Peter', 'Okeyo', 'peter.okeyo@example.com', 'hash_okeyo_pwd', '+254711987654', 'host'),
(@guest_sandra_id, 'Sandra', 'Johnson', 'sandra.j@example.com', 'hash_sandra_pwd', '+1-202-555-0199', 'guest'),
(@guest_ali_id, 'Ahmed', 'Ali', 'ahmed.ali@example.com', 'hash_ali_pwd', '+254733112233', 'guest'),
(@admin_user_id, 'Admin', 'User', 'admin@alxairbnb.com', 'hash_admin_pwd', NULL, 'admin');


-- -----------------------------------------------------
-- Step 2: Insert Properties
-- -----------------------------------------------------
INSERT INTO Property (property_id, host_id, name, description, location, price_per_night) VALUES
(@prop_kilimani_id, @host_wambui_id, 'Serene Studio in Kilimani', 'A quiet and modern studio apartment perfect for business travelers. Includes Wi-Fi and a dedicated workspace.', 'Kilimani, Nairobi', 6500.00),
(@prop_runda_id, @host_wambui_id, 'Spacious Runda Villa with Garden', 'A beautiful 4-bedroom villa in the heart of Runda. Perfect for families, with a large private garden and swimming pool.', 'Runda, Nairobi', 28000.00),
(@prop_limuru_id, @host_okeyo_id, 'Cozy Farmhouse Cottage in Limuru', 'Escape the city to this peaceful cottage surrounded by tea fields in Kiambu County. Fresh air and stunning views guaranteed.', 'Limuru, Kiambu County', 9500.00);


-- -----------------------------------------------------
-- Step 3: Insert Bookings
-- -----------------------------------------------------
INSERT INTO Booking (booking_id, property_id, user_id, start_date, end_date, total_price, status) VALUES
-- Past booking by Sandra at the Kilimani Studio
(@booking1_id, @prop_kilimani_id, @guest_sandra_id, '2025-05-10', '2025-05-15', 32500.00, 'confirmed'),
-- Current booking by Ahmed Ali at the Limuru cottage
(@booking2_id, @prop_limuru_id, @guest_ali_id, '2025-06-28', '2025-06-30', 19000.00, 'confirmed'),
-- Future booking by Sandra at the Runda Villa
(@booking3_id, @prop_runda_id, @guest_sandra_id, '2025-08-20', '2025-08-27', 196000.00, 'pending');


-- -----------------------------------------------------
-- Step 4: Insert Payments for Bookings
-- -----------------------------------------------------
INSERT INTO Payment (payment_id, booking_id, amount, payment_method) VALUES
(UUID(), @booking1_id, 32500.00, 'credit_card'), -- Full payment for Sandra's past booking
(UUID(), @booking2_id, 19000.00, 'paypal'), -- Full payment for Ahmed's current booking
(UUID(), @booking3_id, 98000.00, 'stripe'); -- 50% deposit for Sandra's future booking


-- -----------------------------------------------------
-- Step 5: Insert Reviews for Completed Bookings
-- -----------------------------------------------------
INSERT INTO Review (review_id, property_id, user_id, rating, comment) VALUES
(UUID(), @prop_kilimani_id, @guest_sandra_id, 5, 'Grace was a wonderful host! The apartment was sparkling clean, comfortable, and in a very convenient location. I would definitely stay here again.');


-- -----------------------------------------------------
-- Step 6: Insert Messages between Users
-- -----------------------------------------------------
INSERT INTO Message (message_id, sender_id, recipient_id, message_body) VALUES
-- Message from guest Ahmed to host Peter before his stay
(UUID(), @guest_ali_id, @host_okeyo_id, 'Hello Peter, looking forward to my stay! Could you please confirm if there is a coffee maker in the cottage?'),
-- Response from host Peter to guest Ahmed
(UUID(), @host_okeyo_id, @guest_ali_id, 'Hi Ahmed, absolutely! There is a French press and we provide some fresh local coffee. See you on the 28th!');

-- =================================================================
-- Seeding Complete.
-- =================================================================